apiVersion: v1
kind: Service
metadata:
  name: basic-quarkus-active
spec:
  selector:
    app: basic-quarkus
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: basic-quarkus-preview
spec:
  selector:
    app: basic-quarkus
  ports:
  - port: 80
    targetPort: 8080
